defaults:
  - _self_
  - streams: frame_dir_stream_emjay  
  - pipeline: default_emjay
  - override hydra/hydra_logging: none
  - override hydra/job_logging: disabled

ray: false
prefilter: false

# GPU 메모리 사전 할당 설정
gpu_id: 0
preallocate_gpu_memory_gb: 42.0

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
