defaults:
  - _self_
  - streams: frame_dir_stream_emjay  
  - pipeline: default_emjay
  - override hydra/hydra_logging: none
  - override hydra/job_logging: disabled

ray: false
prefilter: false

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
